# You will need to connect to the container and execute train.sh to start the training

version: "3.7"
services:
  Darknet:
    image: alex1075/darknet:latest
    ports:
     - 8070:8070
     - 8090:8090
    volumes:
     - ./data:/darknet/data  # pass your images/annotations files through 
     - .cfg:/darknet/cfg # pass your weights/config files through 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    depends_on:
      - phd-tensorboard
  Tensorboard:
    image: alex1075/tensorboard:latest
    volumes:
     - ./data:/data #location of logfiles 
    restart: aleways
    ports:
      - 6006:6006   
