version: "3.7"
services:
  PhD-YOLO:
    image: alex1075/darknet:latest
    volumes:
     - ./data:/darknet/data  # pass your images/annotations files through 
     - .cfg:/darknet/cfg # pass your weights/config files through 
     - train.sh:/darknet/train.sh # required! container will look for train.sh file. WILL NOT RUN WITHOUT
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    depends_on:
      - phd-tensorboard
  PhD-tensorboard:
    image: alex1075/tensorboard:latest
    volumes:
     - ./data:/data #location of logfiles 
    restart: aleways
    ports:
      - 6006:6006   
